EasyAccomod/Controllers/AdminManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EasyAccomod.Models;

namespace EasyAccomod.Controllers
{
    public class AdminManagerController : Controller
    {
        // GET: Manager
        public ActionResult Index()
        {
            int usertype;
            if (Session["userid"] == null || Session["usertype"] == null || !int.TryParse(Session["usertype"].ToString(), out usertype)) return RedirectToAction("SignIn", "Account");
            if (usertype != 1) return Content("<a href='/Account/SignOut'>Đăng nhập lại</a> với tài khoản admin để sử dụng chức năng này", "text/html");
            return View();
        }

        [HttpGet]
        public ActionResult ApproveAccount()
        {
            using (var db = new DBContext())
            {
                var accounts = (from a in db.Accounts
                             where a.Type == 2 && a.Approved == false && a.ApprovalTime.Year <= 2000
                             select a).ToList();
                return PartialView(accounts);
            }
        }

        [HttpPost]
        public JsonResult ApproveAccount(int id)
        {
            int userid, usertype;
            if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) return Json("SignInFirst");
            if (Session["usertype"] == null || !int.TryParse(Session["usertype"].ToString(), out usertype) || usertype != 1) return Json("AdminOnly");
            try
            {
                using (var db = new DBContext())
                {
                    var account = (from a in db.Accounts
                                   where a.Id == id
                                   select a).FirstOrDefault();
                    if (account.Approved || (account.Approved && account.ApprovalTime.Year > 1)) return Json("AccountProccessed");
                    account.Approved = true;
                    account.ApprovalTime = DateTime.Now;
                    account.ApproverId = userid;
                    account.EditRole = false;
                    db.SaveChanges();
                    return Json("Success");
                }
            }
            catch (Exception ex) { return Json(ex.Message); }
        }

        [HttpPost]
        public JsonResult RefuseAccount(int id)
        {
            int userid, usertype;
            if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) return Json("SignInFirst");
            if (Session["usertype"] == null || !int.TryParse(Session["usertype"].ToString(), out usertype) || usertype != 1) return Json("AdminOnly");
            using (var db = new DBContext())
            {
                var account = (from a in db.Accounts
                               where a.Id == id
                               select a).FirstOrDefault();
                if (account.Approved || (account.Approved && account.ApprovalTime.Year > 1)) return Json("AccountProccessed");
                account.ApprovalTime = DateTime.Now;
                account.ApproverId = userid;
                db.SaveChanges();
                return Json("Success");
            }
        }

        [HttpPost]
        public JsonResult ApprovePost(int id)
        {
            if (Session["userid"] == null || Session["usertype"] == null) return Json("SignInFirst");
            int userid, usertype = 0;
            if (!int.TryParse(Session["userid"].ToString(), out userid) || !int.TryParse(Session["usertype"].ToString(), out usertype) || usertype != 1) return Json("AdminOnly");
            using (var db = new DBContext())
            {
                var ticket = (from t in db.Tickets
                              where t.Id == id && t.Approved == 0 && t.ApprovalTime.Year < 2000
                              select t).FirstOrDefault();
                if (ticket == null) return Json("TicketNotFound");
                if (ticket.Approved != 0) return Json("TicketProcessed");
                ticket.ApproverId = userid;
                ticket.ApprovalTime = DateTime.Now;
                ticket.Approved = 1;
                db.Entry(ticket)
                    .Reference(x => x.Post)
                    .Load();
                if (ticket.Post.Approved == -1) return Json("PostRefued");
                //if (ticket.Post.EndTime >= DateTime.Now && ticket.Post.Approved == 1 && ticket.Post.IsShow) return Json("PostShowed");
                ticket.Post.Approved = 1;
                ticket.Post.IsShow = true;
                ticket.Post.StartTime = DateTime.Now;
                switch (ticket.UnitTime)
                {
                    case 1:
                        ticket.Post.EndTime = ticket.Post.StartTime.AddDays(ticket.Time * 7);
                        break;
                    case 2:
                        ticket.Post.EndTime = ticket.Post.StartTime.AddMonths(ticket.Time);
                        break;
                    case 3:
                        ticket.Post.EndTime = ticket.Post.StartTime.AddMonths(ticket.Time * 3);
                        break;
                    case 4:
                        ticket.Post.EndTime = ticket.Post.StartTime.AddYears(ticket.Time);
                        break;
                    default:
                        ticket.Post.EndTime = ticket.Post.StartTime;
                        break;
                }
                db.SaveChanges();
            }
            return Json("Success");
        }

        [HttpPost]
        public JsonResult RefusePost(int id)
        {
            if (Session["userid"] == null || Session["usertype"] == null) return Json("SignInFirst");
            int userid, usertype = 0;
            if (!int.TryParse(Session["userid"].ToString(), out userid) || !int.TryParse(Session["usertype"].ToString(), out usertype) || usertype != 1) return Json("AdminOnly");
            using (var db = new DBContext())
            {
                var ticket = (from t in db.Tickets
                              where t.Id == id && t.Approved == 0
                              select t).FirstOrDefault();
                if (ticket == null) return Json("TicketNotFound");
                if (ticket.Approved != 0) return Json("TicketProcessed");
                ticket.ApproverId = userid;
                ticket.ApprovalTime = DateTime.Now;
                ticket.Approved = -1;
                db.Entry(ticket)
                    .Reference(x => x.Post)
                    .Load();
                if (ticket.Post.Approved == -1) return Json("PostRefued");
                if (ticket.Post.EndTime >= DateTime.Now && ticket.Post.Approved == 1 && ticket.Post.IsShow) return Json("PostShowed");
                ticket.Post.IsShow = false;
                if (ticket.Post.Approved == 0) ticket.Post.Approved = -1;
                db.SaveChanges();
            }
            return Json("Success");
        }

        [HttpGet]
        public ActionResult ApproveComment()
        {
            using (var db = new DBContext())
            {
                var comments = (from c in db.Comments
                                where (!c.Approved) && (c.ApprovalTime.Year <= 1)
                                select c).ToList();
                foreach (var item in comments)
                {
                    db.Entry(item)
                        .Reference(x => x.Post)
                        .Load();
                    db.Entry(item)
                        .Reference(x => x.User)
                        .Load();
                    db.Entry(item.Post)
                        .Reference(x => x.Poster)
                        .Load();
                    db.Entry(item.Post)
                        .Reference(x => x.City)
                        .Load();
                    db.Entry(item.Post)
                        .Reference(x => x.District)
                        .Load();
                    db.Entry(item.Post)
                        .Reference(x => x.Ward)
                        .Load();
                    db.Entry(item.Post)
                        .Collection(x => x.Images)
                        .Load();
                }
                return PartialView(comments);
            }
        }

        [HttpPost]
        public JsonResult ApproveComment(int id)
        {
            int userid, usertype;
            if (Session["userid"] == null || Session["usertype"] == null || !int.TryParse(Session["userid"].ToString(), out userid) || !int.TryParse(Session["usertype"].ToString(), out usertype)) return Json("SignInFirst");
            if (usertype != 1) return Json("AdminOnly");
            try
            {
                using (var db = new DBContext())
                {
                    var comment = (from c in db.Comments
                                   where c.Id == id
                                   select c).FirstOrDefault();
                    if (comment == null) { return Json("CommentNotFound"); }
                    if (comment.ApprovalTime.Year > 1) return Json("CommentProcessed");
                    comment.ApprovalTime = DateTime.Now;
                    comment.ApproverId = userid;
                    comment.Approved = true;
                    db.SaveChanges();
                }
                return Json("Success");
            }
            catch (Exception ex) { return Json(ex.Message); }
        }

        [HttpPost]
        public JsonResult RefuseComment(int id)
        {
            int userid, usertype;
            if (Session["userid"] == null || Session["usertype"] == null || !int.TryParse(Session["userid"].ToString(), out userid) || !int.TryParse(Session["usertype"].ToString(), out usertype)) return Json("SignInFirst");
            if (usertype != 1) return Json("AdminOnly");
            try
            {
                using (var db = new DBContext())
                {
                    var comment = (from c in db.Comments

EasyAccomod/Controllers/PostPriceController.cs
using EasyAccomod.Helpers;
using EasyAccomod.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyAccomod.Controllers
{
    public class PostPriceController : Controller
    {
        // GET: PostPrice
        public JsonResult Index(int TimeLength, int TimeUnit)
        {
            try
            {
                using (var db = new DBContext())
                {
                    int postPrice = (from pp in db.PostPrices
                                     where pp.Type == TimeUnit
                                     select pp.Price).FirstOrDefault();
                    int amount = TimeLength * postPrice;
                    
                    return Json(amount.ToVND(), JsonRequestBehavior.AllowGet);
                }
            }
            catch { return Json("Đã xảy ra lỗi trong quá trình kiểm tra số tiền phải thanh toán", JsonRequestBehavior.AllowGet); }
        }
    }
}

EasyAccomod/Views/AdminManager/ApproveAccount.cshtml
@model IEnumerable<EasyAccomod.Models.AccountModel>

<style>
    
    .user-info p {
        margin-bottom:0;
    }
</style>
<div id="approve-account-container">
<h5 class="my-4">Phê duyệt tài khoản</h5>

@if (Model != null)
{
    foreach (var item in Model)
    {
        <div class="container account-card">
            <div class=" rounded border mb-4 p-2">
                <span style="display: inline-block;"><b>@item.Username</b></span>
                <div class="user-info ml-5">
                    <p>Họ và tên: @item.FullName</p>
                    <p>Số điện thoại: @item.Phone</p>
                    <p>Email: @item.Email</p>
                    <p>CCCD: @item.IdCard</p>
                </div>
                <div class="confirm-bar text-right">
                    <button class="btn btn-primary approve-account-button" data-accountid="@item.Id">Phê duyệt</button>
                    <button class="btn btn-secondary ml-3 refuse-account-button" data-accountid="@item.Id">Từ chối</button>
                </div>
                <div class="err-container" style="color: red"></div>
            </div>
        </div>
    }
}
</div>

<script>
    $("#approve-account-container").delegate(".approve-account-button", "click", function (e) {
        if ($(e.target).prop("disabled")) return;
        $(e.target).prop("disabled", true);
        $.ajax({
            url: "/AdminManager/ApproveAccount",
            type: "POST",
            data: { id: $(e.target).attr("data-accountid") },
            success: function (data) {
                if (data == "Success") {
                    $(e.target).parents(".account-card").remove();
                    ShowActionSuccessPopup("Phê duyệt tài khoản thành công!");
                    return;
                }
                console.log(data);
                console.log($(e.target).parents(".account-card").find(".err-container"));
                $(e.target).parents(".account-card").find(".err-container")[0].innerText = data;
                $(e.target).prop("disabled", false);
            }
        });
    });
    $("#approve-account-container").delegate(".refuse-account-button", "click", function (e) {
        if ($(e.target).prop("disabled")) return;
        $(e.target).prop("disabled", true);
        $.ajax({
            url: "/AdminManager/RefuseAccount",
            type: "POST",
            data: { id: $(e.target).attr("data-accountid") },
            success: function (data) {
                if (data == "Success") {
                    $(e.target).parents(".account-card").remove();
                    ShowActionSuccessPopup("Từ chối tài khoản thành công!");
                    return;
                }
                $(e.target).parents(".account-card").find(".err-container")[0].innerText = data;
                $(e.target).prop("disabled", false);
            }
        });
    });
</script>

EasyAccomod/Views/AdminManager/ApproveComment.cshtml
@model IEnumerable<EasyAccomod.Models.CommentModel>

<link href="~/Content/ApproveComment.css" rel="stylesheet" />
<div id="approve-comment-container">
        <h5 class="my-4">Phê duyệt bình luận</h5>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <!--One card-->
                <div class="container comment-card">
                    <div class=" rounded border mb-4 p-2">
                        <div class="post-wrapper row px-3">
                            @if (item == null || item.Post == null || item.Post.Images == null || item.Post.Images.Count == 0)
                            {
                                <div class="post-image-thumb"></div>
                            }
                            else
                            {
                                <div class="post-image-thumb" style="background: url('/UploadImage/@item.Post.Images.First().Path'); background-size: 100% 100%"></div>
                            }
                            <div class="post-info col-12 col-lg-9">
                                <div class="post-top-part">
                                    <span class="post-title">
                                        @item.Post.Title
                                    </span>
                                    <span class="post-address">
                                        @item.Post.Address - @item.Post.Ward.WardName - @item.Post.District.DistrictName - @item.Post.City.CityName
                                    </span>
                                    @{ string area = item.Post.Area + "m2";}
                                    <span class="post-area">@area</span>
                                    <span class="post-price">@item.Post.DisplayPrice()</span>
                                </div>
                                <span class="post-user">@item.Post.Poster.FullName</span>
                                <span class="post-datetime">@item.Post.CreateTime</span>


                            </div>
                        </div>
                        <hr>
                        <div class="row px-3">
                            <p><b>@item.User.FullName</b></p>
                        </div>
                        <div class="row px-3">
                            <p>14:59 26/12/20</p>
                        </div>
                        <div class="row px-3">
                            <p>@item.Content</p>
                        </div>

                        <div class="confirm-bar text-right">
                            <div class="btn btn-primary comment-approve" data-id="@item.Id">Phê duyệt</div>
                            <div class="btn btn-secondary ml-3 comment-refuse" data-id="@item.Id">Từ chối</div>
                        </div>
                    </div>
                </div>

                <!--End card-->
            }
        }

   
    </div>
<script>
    $("#approve-comment-container").delegate(".comment-approve", "click", function (e) {
        if ($(e.target).prop("disabled")) return;
        $(e.target).prop("disabled", true);
        $(".comment-refuse[data-id=" + $(e.target).attr("data-id") + "]").prop("disabled", true);
        $.ajax({
            url: "/AdminManager/ApproveComment",
            type: "POST",
            data: { id: $(e.target).attr("data-id") },
            success: function (data) {
                if (data == "Success") {
                    $(e.target).parents(".comment-card").remove();
                    ShowActionSuccessPopup("Phê duyệt bình luận thành công!");
                    return;
                }
                alert(data);
                $(e.target).prop("disabled", false);
                $(".comment-refuse[data-id=" + $(e.target).attr("data-id") + "]").prop("disabled", false);
            }
        });
    });
    $("#approve-comment-container").delegate(".comment-refuse", "click", function (e) {
        if ($(e.target).prop("disabled")) return;
        $(e.target).prop("disabled", true);
        $(".comment-approve[data-id=" + $(e.target).attr("data-id") + "]").prop("disabled", true);
        $.ajax({
            url: "/AdminManager/RefuseComment",
            type: "POST",
            data: { id: $(e.target).attr("data-id") },
            success: function (data) {
                if (data == "Success") {
                    $(e.target).parents(".comment-card").remove();
                    ShowActionSuccessPopup("Xoá bình luận thành công!");
                    return;
                }
                alert(data);
                $(e.target).prop("disabled", false);
                $(".comment-refuse[data-id=" + $(e.target).attr("data-id") + "]").prop("disabled", false);
            }
        });
    });
</script>

EasyAccomod/Views/AdminManager/ApprovePost.cshtml
@{
    Layout = null;
}

@model IEnumerable<EasyAccomod.Models.TicketModel>

<link href="~/Content/ApprovePost.css" rel="stylesheet" />
<h5 class="my-4">Phê duyệt bài đăng</h5>
@foreach (var item in Model)
{
    <div class="container post-card">
        <div class=" rounded border mb-4 p-2">
            <div class="post-wrapper row px-3">
                @if (item == null || item.Post == null || item.Post.Images == null || item.Post.Images.Count == 0)
                {
                    <div class="post-image-thumb"></div>
                }
                else
                {
                    <div class="post-image-thumb" style="background: url('/UploadImage/@item.Post.Images.First().Path'); background-size: 100% 100%"></div>
                }
                <div class="post-info col-12 col-lg-9">
                    <div class="post-top-part">
                        <span class="post-title">@item.Post.Title</span>
                        <span class="post-address">@item.Post.Address - @item.Post.Ward.WardName - @item.Post.District.DistrictName - @item.Post.City.CityName</span>
                        @{
                            string area = item.Post.Area + "m2";
                        }
                        <span class="post-area">@area</span>
                        <span class="post-price">@item.Post.DisplayPrice()</span>
                    </div>
                    <span class="post-user">@item.Post.Poster.FullName</span>
                    <span class="post-datetime">@item.CreateTime</span>


                </div>
            </div>

            <div class="confirm-bar text-right">
                <div style="float: left; font-size: 16px; color: green">
                    @if (item.Post.Approved == 0)
                    {
                        <span><i>Bài đăng mới</i></span>
                    }
                    @if (item.Post.Approved == 1)
                    {
                        <span><i>Gia hạn bài đăng</i></span>
                    }
                    <span> - Thời gian hiển thị: @item.GetTime()</span>
                </div>
                <button class="btn btn-primary approve-post-button" data-postid="@item.Id">Phê duyệt</button>
                <button class="btn btn-secondary ml-3 refuse-post-button" data-postid="@item.Id">Từ chối</button>
            </div>
            <div class="err-container" style="text-align: left; color: red"></div>
        </div>
    </div>
}

<script>
    $(".approve-post-button").click(function (e) {
        if ($(e.target).prop("disabled")) return;
        $(e.target).prop("disabled", true);
        $.ajax({
            url: "/AdminManager/ApprovePost",
            type: 'POST',
            data: { id: $(e.target).attr("data-postid") },
            success: function (data) {
                if (data == "Success") {
                    $(e.target).parents(".post-card").remove();
                    ShowActionSuccessPopup("Phê duyệt bài đăng thành công!");
                    return;
                }
                $(e.target).prop("disabled", false);
                $(e.target).parents(".post-card").find(".err-container")[0].innerHTML = data;
            }
        })
    })
    $(".refuse-post-button").click(function (e) {
        if ($(e.target).prop("disabled")) return;
        $(e.target).prop("disabled", true);
        $.ajax({
            url: "/AdminManager/RefusePost",
            type: 'POST',
            data: { id: $(e.target).attr("data-postid") },
            success: function (data) {
                if (data == "Success") {
                    $(e.target).parents(".post-card").remove();
                    ShowActionSuccessPopup("Bạn đã từ chối bài đăng! Có thể hoàn tác tại mục Bài đăng đã huỷ");
                    return;
                }
                $(e.target).prop("disabled", false);
                $(e.target).parents(".post-card").find(".err-container")[0].innerHTML = data;
            }
        })
    })
</script>

EasyAccomod/Views/AdminManager/ApprovePurchase.cshtml
@model IEnumerable<EasyAccomod.Models.PostModel> 
<link href="~/Content/ApprovePurchase.css" rel="stylesheet" />

        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="approve-purchase-container" role="tabpanel">
                <h5 class="my-4">Phê duyệt gia hạn bài đăng</h5>
                @foreach (var item in Model)
                {
                <!--One card-->
                <div class="container post-card">
                    <div class=" rounded border mb-4 p-2">
                        <div class="post-wrapper row px-3">
                            @if (item == null || item.Images == null || item.Images.Count == 0)
                            {
                                <div class="post-image-thumb"></div>
                            }
                            else
                            {
                                <div class="post-image-thumb" style="background: url('/UploadImage/@item.Images.First().Path'); background-size: 100% 100%"></div>
                            }
                            <div class="post-info col-12 col-lg-9">
                                <div class="post-top-part">
                                    <span class="post-title"> @item.Title</span>
                                    <span class="post-address">@item.Address - @item.Ward.WardName - @item.District.DistrictName - @item.City.CityName</span>
                                    @{
                                        string area = item.Area + "m2";
                                    }
                                    <span class="post-area">@area</span>
                                    <span class="post-price">@item.DisplayPrice()</span>
                                </div>
                                <span class="post-user">@item.Poster.FullName</span>
                                <span class="post-datetime">@item.CreateTime</span>


                            </div>
                        </div>
                        <hr>
                        <div class="row px-3">
                            <p>Thời gian gia hạn: @item.ApprovalTicket.GetTime()</p>
                        </div>
                        <div class="row px-3">
                            <p>Số tiền: @{Html.RenderAction("Index", "PostPrice", new { TimeLength = item.ApprovalTicket.Time, TimeUnit = item.ApprovalTicket.UnitTime }); }</p>
                        </div>

                        <div class="confirm-bar text-right">
                            <button class="btn btn-primary approve-post-button" data-postid="@item.Id">Phê duyệt</button>
                            <button class="btn btn-secondary ml-3 refuse-post-button" data-postid="@item.Id">Từ chối</button>
                        </div>
                        <div class="err-container" style="text-align: left; color: red"></div>
                    </div>  
                </div>

                <!--End card-->
                }

            </div>
        </div>
        <script>
            $(".approve-post-button").click(function (e) {
                if ($(e.target).prop("disabled")) return;
                $(e.target).prop("disabled", false);
                $.ajax({
                    url: "/AdminManager/ApprovePost",
                    type: 'POST',
                    data: { id: $(e.target).attr("data-postid") },
                    success: function (data) {
                        if (data == "Success") {
                            $(e.target).parents(".account-card").remove();
                            ShowActionSuccessPopup("Bạn đã gia hạn bài đăng thành công! Giờ đây bài đăng có thể hiển thị với mọi người.");
                            return;
                        }
                        $(e.target).prop("disabled", true);
                        $(e.target).parents(".post-card").find(".err-container")[0].innerHTML = data;
                    }
                })
            })
            $(".refuse-post-button").click(function (e) {
                if ($(e.target).prop("disabled")) return;
                $(e.target).prop("disabled", false);
                $.ajax({
                    url: "/AdminManager/RefusePost",
                    type: 'POST',
                    data: { id: $(e.target).attr("data-postid") },
                    success: function (data) {
                        if (data == "Success") {
                            $(e.target).parents(".account-card").remove();
                            ShowActionSuccessPopup("Bạn đã huỷ gia hạn bài đăng!");
                            return;
                        }
                        $(e.target).prop("disabled", true);
                        $(e.target).parents(".post-card").find(".err-container")[0].innerHTML = data;
                    }
                })
            })
        </script>

EasyAccomod/Views/AdminManager/ApprovedAccount.cshtml
@model IEnumerable<EasyAccomod.Models.AccountModel>


<style>

    .user-info p {
        margin-bottom: 0;
    }
</style>
<div id="approved-account-container">
<h5 class="my-4">Tài khoản chủ trọ đã phê duyệt</h5>

@if (Model != null)
{
    foreach (var item in Model)
    {
        <div class="container account-card">
            <div class=" rounded border mb-4 p-2">
                <span style="display: inline-block;"><b>@item.Username</b></span>
                <div class="user-info ml-5">
                    <p>Họ và tên: @item.FullName</p>
                    <p>Số điện thoại: @item.Phone</p>
                    <p>Email: @item.Email</p>
                    <p>CCCD: @item.IdCard</p>
                </div>
                <div class="confirm-bar" style="text-align: right; padding-top: 10px;">
                    <div style="float: left; text-align: left">
                        <span>Người phê duyệt: @item.Approver.FullName</span> <br />
                        <span>Thời gian phê duyệt: @item.ApprovalTime</span>
                    </div>
                    @if (!item.EditRole)
                    {
                        <button class="btn btn-primary authorize-account-button" data-accountid="@item.Id">Cấp quyền chỉnh sửa</button>
                    }
                    else
                    {
                        <button class="btn btn-primary unauthorize-account-button" data-accountid="@item.Id">Thu hồi quyề chỉnh sửa</button>
                    }
                </div>
                <div class="err-container" style="color: red">

                </div>
            </div>
        </div>
    }
}
</div>


<script>
    $("#approved-account-container").delegate(".authorize-account-button", "click", function (e) {
        if ($(e.target).prop("disabled")) return;
        $(e.target).prop("disabled", true);
        $.ajax({
            url: "/AdminManager/AuthorizeAccount",
            type: "POST",
            data: { id: $(e.target).attr("data-accountid") },
            success: function (data) {
                if (data == "Success") {
                    $(e.target)[0].innerText = "Thu hồi quyền chỉnh sửa";
                    $(e.target).removeClass("authorize-account-button");
                    $(e.target).addClass("unauthorize-account-button");
                    $(e.target).prop("disabled", false);
                    ShowActionSuccessPopup("Cấp quyền chỉnh sửa cho tài khoản thành công!");
                    return;
                }
                $(e.target).parents(".account-card").find(".err-container")[0].innerHTML = data;
                $(e.target).prop("disabled", false);
            }
        });
    });

    $("#approved-account-container").delegate(".unauthorize-account-button", "click", function (e) {
        if ($(e.target).prop("disabled")) return;
        $(e.target).prop("disabled", true);
        $.ajax({
            url: "/AdminManager/UnauthorizeAccount",
            type: "POST",
            data: { id: $(e.target).attr("data-accountid") },
            success: function (data) {
                if (data == "Success") {
                    $(e.target)[0].innerText = "Cấp quyền chỉnh sửa";
                    $(e.target).removeClass("unauthorize-account-button");
                    $(e.target).addClass("authorize-account-button");
                    $(e.target).prop("disabled", false);
                    return;
                }
                $(e.target).parents(".account-card").find(".err-container")[0].innerHTML = data;
                $(e.target).prop("disabled", false);
            }
        });
    });
</script>