EasyAccomod/Controllers/HostManagerController.cs
using EasyAccomod.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyAccomod.Controllers
{
    public class HostManagerController : Controller
    {
        public ActionResult Index()
        {
            if (Session["userid"] == null || Session["usertype"] == null) return RedirectToAction("SignIn", "Account");
            int userid, usertype;
            if (int.TryParse(Session["usertype"].ToString(), out usertype) && int.TryParse(Session["userid"].ToString(), out userid) && usertype != 1 && usertype != 2) return Json("Access Deny", JsonRequestBehavior.AllowGet);
            return View();
        }
        public ActionResult Post()
        {
            if (Session["userid"] == null) return RedirectToAction("SignIn", "Account");
            int userid;
            if (!(int.TryParse(Session["userid"].ToString(), out userid))) RedirectToAction("SignIn", "Account");
            using (var db = new DBContext())
            {
                var posts = (from p in db.Posts
                             where p.PosterId == userid
                             select p).ToList();
                foreach (var item in posts)
                {
                    db.Entry(item)
                        .Reference(x => x.City)
                        .Load();
                    db.Entry(item)
                        .Reference(x => x.District)
                        .Load();
                    db.Entry(item)
                        .Reference(x => x.Ward)
                        .Load();
                    db.Entry(item)
                        .Collection(x => x.Images)
                        .Load();
                    db.Entry(item)
                        .Collection(x => x.Tickets)
                        .Load();
                }
                HostPostsModel model = new HostPostsModel();
                model.ShowingPost = (from p in posts
                                     where p.Approved == 1
                                        && p.IsShow
                                        && !p.Sold
                                        && p.EndTime >= DateTime.Now
                                     orderby p.EndTime
                                     select p).ToList();
                model.ApprovingPost = (from p in posts
                                       where p.Approved == 0
                                            || (p.Approved == 1 && p.Tickets.Where(x => x.ApprovalTime.Year <= 2000).Count() > 0)
                                        orderby p.CreateTime descending
                                       select p).ToList();
                model.SoldPost = (from p in posts
                                    where p.Sold
                                    orderby p.CreateTime
                                    select p).ToList();
                model.ExpiredPost = (from p in posts
                                     where p.Approved == 1
                                        && p.IsShow
                                        && p.EndTime < DateTime.Now
                                     orderby p.EndTime descending
                                     select p).ToList();
                model.RefusedPost = (from p in posts
                                    where p.Approved == -1
                                    orderby p.CreateTime descending
                                    select p).ToList();
                foreach (var item in model.ApprovingPost)
                {
                    item.ApprovalTicket = (from t in item.Tickets
                                           where t.Approved == 0 && t.ApprovalTime.Year <= 2000
                                           select t).FirstOrDefault();
                }
                return PartialView(model);
            }
        }

        [HttpPost]
        public JsonResult ChangePostStatus(int id, bool sold)
        {
            try
            {
                int userid = 0;
                if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) Json("SignInFirst");
                using (var db = new DBContext())
                {
                    var post = (from p in db.Posts
                                where p.Id == id
                                select p).FirstOrDefault();
                    if (post.PosterId != userid) return Json("NotOwned");
                    if (post == null) return Json("PostNotFound");
                    if (post.Sold == sold) return Json("Proccessed");
                    post.Sold = sold;
                    db.SaveChanges();
                }
                return Json("Success");
            }
            catch (Exception ex) { return Json(ex.Message); }
        }

        [HttpPost]
        public JsonResult DeletePost(int id)
        {
            try
            {
                int userid = 0;
                if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) Json("SignInFirst");
                using (var db = new DBContext())
                {
                    var post = (from p in db.Posts
                                where p.Id == id
                                select p).FirstOrDefault();
                    if (post.PosterId != userid) return Json("NotOwned");
                    if (post == null) return Json("PostNotFound");
                    db.Posts.Remove(post);
                    db.SaveChanges();
                }
                return Json("Success");
            }
            catch (Exception ex) { return Json(ex.Message); }
        }

        [HttpPost]
        public JsonResult ExtendPost(int id, int timeUnit, int timeLength)
        {
            try
            {
                int userid = 0;
                if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) return Json("SignInFirst");
                TicketModel ticket = new TicketModel();
                ticket.PostId = id;
                ticket.CreateTime = DateTime.Now;
                ticket.Time = timeLength;
                ticket.UnitTime = timeUnit;
                ticket.ApproverId = userid;
                using (var db = new DBContext())
                {
                    var account = (from a in db.Accounts
                                   where a.Id == userid
                                   select a).FirstOrDefault();
                    if (account == null) return Json("SignInFirst");
                    var post = (from p in db.Posts
                                where p.Id == id
                                select p).FirstOrDefault();
                    if (post == null) return Json("PostNotFound");
                    if (post.PosterId != userid) return Json("NotOwned");
                    post.Sold = false;
                    db.Tickets.Add(ticket);
                    db.SaveChanges();
                    return Json("Success");
                }
            }
            catch (Exception ex) { return Json(ex.Message); }
        }

        public ActionResult ExtendPostBox(int id)
        {
            return PartialView("ExtendPostBox", id.ToString());
        }
    }
}

EasyAccomod/Controllers/PostController.cs
using EasyAccomod.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace EasyAccomod.Controllers
{
    public class PostController : Controller
    {
        public ActionResult Index(int id)
        {
            return View();
        }

        [HttpGet]
        public ActionResult CreatePost()
        {
            int userid;
            if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) return PartialView("../Account/SignIn", new SignInModel());
            using (var db = new DBContext())
            {
                var account = (from a in db.Accounts
                               where a.Id == userid
                                && (a.Type == 1 || (a.Type == 2 && a.Approved && a.ApprovalTime.Year != 0))
                               select a).FirstOrDefault();
                if (account == null) return PartialView("CreatePostAccessDeny");
            }
            return View(new CreatePostModel());
        }

        [HttpPost]
        public ContentResult CreatePost(CreatePostModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelError err = ModelState.Values.Where(x => x.Errors.Count() != 0).First().Errors[0];
                return Content(err.ErrorMessage, "text/html");
            }
            try
            {
                PostModel newPost = new PostModel();
                newPost.Address = model.Address;
                newPost.CityId = model.CityId;
                newPost.DistrictId = model.DistrictId;
                newPost.WardId = model.WardId;
                newPost.Price = model.Price;
                newPost.PriceUnit = model.PriceUnit;
                newPost.Type = model.Type;
                newPost.Area = model.Area;
                if (model.ElectricityBase) newPost.ElectricityPrice = -1;
                else newPost.ElectricityPrice = model.ElectricityPrice;
                if (model.WaterBase) newPost.WaterPrice = -1;
                else newPost.WaterPrice = model.WaterPrice;
                newPost.AirConditioner = (model.AirConditioner) ? 1 : 0;
                newPost.WaterHeater = (model.WaterHeater) ? 1 : 0;
                newPost.PrivateKitchen = (model.PrivateKitchen) ? 1 : 0;
                newPost.Balcony = (model.Balcony) ? 1 : 0;
                newPost.ClosedRoom = (model.ClosedRoom) ? 1 : 0;
                newPost.WithoutHost = (model.WithoutHost) ? 1 : 0;
                newPost.PosterId = int.Parse(Session["userid"].ToString());
                newPost.ContactName = Session["fullname"].ToString();
                newPost.CreateTime = DateTime.Now;
                using (var db = new DBContext())
                {
                    var user = (from a in db.Accounts
                                where a.Id == newPost.PosterId
                                select a).FirstOrDefault();
                    if (user == null) return Content("window.location.href = '/Account/SignIn'", "text/javascript");
                    newPost.ContactPhone = user.Phone;
                    if (user.Type == 1)
                    {
                        newPost.StartTime = newPost.CreateTime;
                        newPost.EndTime = newPost.CreateTime.AddDays(7);
                        newPost.Approved = 1;
                        newPost.IsShow = true;
                    }
                }
                newPost.Title = model.Title;
                newPost.Content = model.Content;
                TicketModel ticket = new TicketModel();
                ticket.ApproverId = 0;
                ticket.CreateTime = DateTime.Now;
                ticket.Time = model.TimeLength;
                ticket.UnitTime = model.TimeUnit;
                ticket.ApproverId = newPost.PosterId;
                if (newPost.Approved == 1)
                {
                    ticket.Approved = 1;
                    ticket.ApprovalTime = ticket.CreateTime;
                }
                newPost.Tickets = new List<TicketModel> { ticket };
                newPost.Images = new List<PostImageModel>();
                for (int i = 0; i < model.UploadImages.Count(); i++)
                {
                    var file = model.UploadImages[i];
                    if (file == null) continue;
                    string fileName = newPost.CreateTime.Year
                        + ((newPost.CreateTime.Month < 10) ? "0" : "") + newPost.CreateTime.Month
                        + ((newPost.CreateTime.Day < 10) ? "0" : "") + newPost.CreateTime.Day
                        + ((newPost.CreateTime.Hour < 10) ? "0" : "") + newPost.CreateTime.Hour
                        + ((newPost.CreateTime.Minute < 10) ? "0" : "") + newPost.CreateTime.Minute
                        + ((newPost.CreateTime.Second < 10) ? "0" : "") + newPost.CreateTime.Second
                        + i + newPost.PosterId + Path.GetExtension(file.FileName);
                    file.SaveAs(Server.MapPath("~/UploadImage/" + fileName));
                    newPost.Images.Add(new PostImageModel { Path = fileName });
                }
                using (var db = new DBContext())
                {
                    db.Posts.Add(newPost);
                    db.SaveChanges();
                }

            }
            catch (Exception ex) { return Content(ex.Message, "text/html"); }
            return Content("<script>window.location.href = '/HostManager'</script>", "text/javascript");
        }

        public ActionResult PostDetail(int id)
        {
            try
            {
                using (var db = new DBContext())
                {
                    var post = (from p in db.Posts
                                where p.Id == id
                                select p).FirstOrDefault();
                    db.Entry(post)
                        .Reference(x => x.Poster)
                        .Load();
                    db.Entry(post)
                        .Reference(x => x.Ward)
                        .Load();
                    db.Entry(post.Ward)
                        .Reference(x => x.District)
                        .Load();
                    db.Entry(post.Ward.District)
                        .Reference(x => x.City)
                        .Load();
                    db.Entry(post)
                        .Collection(x => x.Images)
                        .Load();
                    post.Comments = (from c in db.Comments
                                     where c.PostId == post.Id && c.Approved
                                     orderby c.CreateTime
                                     select c).ToList();
                    foreach (var item in post.Comments)
                    {
                        db.Entry(item)
                            .Reference(x => x.User)
                            .Load();
                    }
                    post.Views = post.Views + 1;
                    ViewPostModel viewPost = new ViewPostModel();
                    viewPost.UserId = 0;
                    if (Session["userid"] != null) viewPost.UserId = int.Parse(Session["userid"].ToString());
                    viewPost.PostId = post.Id;
                    viewPost.Time = DateTime.Now;
                    db.ViewPosts.Add(viewPost);
                    db.SaveChanges();
                    return View(post);
                }
            }
            catch { return Json("Đã xảy ra lỗi trong quá trình lấy dữ liệu bài viết", JsonRequestBehavior.AllowGet); }
        }
        [HttpPost]
        public JsonResult CreateComment(int postid, string content)
        {
            try
            {
                int userid, usertype;
                if (Session["userid"] == null || Session["usertype"] == null || !int.TryParse(Session["userid"].ToString(), out userid) || !int.TryParse(Session["usertype"].ToString(), out usertype)) return Json("SignInFirst");
                if (usertype != 3) return Json("RenterOnly");
                CommentModel comment = new CommentModel();
                comment.PostId = postid;
                comment.UserId = userid;
                comment.CreateTime = DateTime.Now;
                comment.Content = content;
                comment.ApproverId = userid;
                using (var db = new DBContext())
                {
                    db.Comments.Add(comment);
                    db.SaveChanges();
                }
            }
            catch (Exception ex) { return Json(ex.Message); }
        return Json("Success");
        }
    }
}

EasyAccomod/Views/HostManager/ExtendPostBox.cshtml
@model string
<div class="overlay"></div>
<div style="background: white; padding: 20px; width: 95%; margin: 50px 2.5%; margin-top: 50px; position: absolute">
    <div class="form-group row">
        <div class="col-12 col-lg-4">
            <label>Thời gian hiển thị</label>
            <input id="TimeLength" class="form-control" type="number" name="TimeLength" value="1" />
        </div>
        <div class="col-12 col-lg-4">
            <label for="time-post-length">&nbsp;</label>
            <select id="TimeUnit" class="form-control" name="TimeUnit">
                <option value="1">Tuần</option>
                <option value="2">Tháng</option>
                <option value="3">Quý</option>
                <option value="4">Năm</option>
            </select>
        </div>
        <div class="col-12 col-lg-4">
            <label for="time-post-length">Số tiền cần thanh toán: </label><br />
            <span id="extend-price" style="color: red; font-weight: bold; font-size: 16px">20.000đ</span>
        </div>
    </div>
    <div class="form-group row" style="padding: 15px">
        <button id="confirm-extend-post" class="btn btn-primary" style="margin-right: 10px" data-postid="@Model">Gia hạn</button>
        <button id="close-extend-post" class="btn btn-primary">Huỷ</button>
    </div>
    <div id="extend-box-err-msg" class="err-msg"></div>
</div>
<script>
    $(".overlay").click(function () {
        $("#extend-post-container").remove();
    });

    $("#close-extend-post").click(function () {
        $("#extend-post-container").remove();
    });
    $("#TimeLength").change(function () {
        updatePrice();
    });
    $("#TimeUnit").change(function () {
        updatePrice();
    })
    function updatePrice() {
        $.ajax({
            url: "/PostPrice",
            type: "POST",
            data: { TimeLength: $("#TimeLength").val(), TimeUnit: $("#TimeUnit").val() },
            success: function (data) {
                $("#extend-price")[0].innerHTML = data;
            }
        })
    }

    $("#confirm-extend-post").click(function () {
        if ($(this).prop("disabled")) return;
        $(this).prop("disabled", true);
        $.ajax({
            url: "/HostManager/ExtendPost",
            type: "POST",
            data: { id: $(this).attr("data-postid"), timeLength: $("#TimeLength").val(), timeUnit: $("#TimeUnit").val() },
            success: function (data) {
                if (data == "Success") {
                    $(".host-mng-extend-post[data-postid='" + $(this).attr("data-postid") + "']").parents("post-card").remove();
                    $("#extend-post-container").remove();
                    return;
                }
                $(this).prop("disabled", false);
                document.getElementById("extend-box-err-msg").innerHTML = data;
            }
        })
    })
</script>

EasyAccomod/Views/HostManager/Index.cshtml
@{
    ViewBag.Title = "Quản lý bài đăng";
}
<link href="~/Content/AdminPostManager.css" rel="stylesheet" />
<link href="~/Content/HostManager.css" rel="stylesheet" />
<div class="admin-page-container container rounded border mx-auto row" style="margin-top: 50px; margin-bottom: 50px;">

    <div class="col-3 web-sidebar" style="position: relative; border-right: 1px solid #eee;">
        <div class="sticky-sidebar">
            <div class="sidebar-header">
                <h3>Quản lý </h3>
            </div>
            <nav id="sidebar">

                <ul class="list-unstyled components">

                    <li class="nav-item-big active">
                        <a id="host-manager-post" href="javascript:void(0)">Bài đăng</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="content col-9" id="content-container" style="min-height:500px;">
        @{Html.RenderAction("Post", "HostManager");}
    </div>

</div>
<script>



    $(".nav-item-big").click(function () {
        if ($(this).attr("aria-expanded", "true")) {
            $(this).find("a").removeClass("active");
        }
        $(this).siblings().find("a").attr("aria-expanded", "false");
        //$(this).siblings().find("ul").removeClass("show");
        if (!$(this).hasClass("active")) {
            $(this).addClass("active");
            $(this).siblings().removeClass("active");
        }
    });


    $("#host-manager-post").click(function () {
        $("#content-container").load("/HostManager/Post");
    });
</script>