EasyAccomod/Controllers/EditInfoController.cs
using EasyAccomod.Helpers;
using EasyAccomod.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyAccomod.Controllers
{
    public class EditInfoController : Controller
    {
        // GET: EditInfo
        public ActionResult Index()
        {
            int userid;
            if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) return RedirectToAction("SignIn", "Account");
            using (var db = new DBContext())
            {
                var account = (from a in db.Accounts
                               where a.Id == userid
                               select a).FirstOrDefault();
                if (account == null) return RedirectToAction("SignOut", "Account");
                return View(account);
            }
        }

        [HttpGet]
        public ActionResult UserInformation()
        {
            int userid;
            if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) return PartialView("/Account/SignIn", new SignInModel());
            using (var db = new DBContext())
            {
                var account = (from a in db.Accounts
                               where a.Id == userid
                               select a).FirstOrDefault();
                if (account == null) return PartialView("/Account/SignIn", new SignInModel());
                db.Entry(account)
                    .Reference(x => x.Ward)
                    .Load();
                db.Entry(account.Ward)
                    .Reference(x => x.District)
                    .Load();
                UserInformationModel model = new UserInformationModel();
                model.Fullname = account.FullName;
                model.Phone = account.Phone;
                model.Email = account.Email;
                model.CityId = account.Ward.District.CityId;
                model.DistrictId = account.Ward.DistrictId;
                model.WardId = account.WardId;
                model.IdCard = account.IdCard;
                model.Address = account.Address;
                model.EditRole = account.EditRole;
                return PartialView(model);
            }
        }

        [HttpPost]
        public ContentResult UserInformation(UserInformationModel model)
        {
            int userid;
            if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) return Content("<script>window.location.href='/Account/SignIn';</script>", "text/javascript");
            try
            {
                using (var db = new DBContext())
                {
                    var account = (from a in db.Accounts
                                   where a.Id == userid
                                   select a).FirstOrDefault();
                    if (account == null) return Content("<script>window.location.href='/Account/SignOut';</script>", "text/javascript");
                    if (!account.EditRole) return Content("<span style='color: red'>Bạn phải được admin cấp quyền chỉnh sửa để có thể chỉnh sửa thông tin cá nhân</span>", "text/html");
                    if (account.Type == 2)
                    {
                        account.Approved = false;
                        account.ApprovalTime = DateTime.MinValue.AddYears(1999);
                    }
                    account.FullName = model.Fullname;
                    account.Phone = model.Phone;
                    account.Email = model.Email;
                    account.IdCard = model.IdCard;
                    account.WardId = model.WardId;
                    account.Address = model.Address;
                    db.SaveChanges();
                    if (account.Type == 2) return Content("Cập nhật thông tin cá nhân thành công. Bạn sẽ không được đăng bài cho đến khi admin duyệt.", "text/html");
                }
                return Content("Cập nhật thông tin cá nhân thành công", "text/html");
            }
            catch (Exception ex) { return Content("<span style='color: red'>" + ex.Message + "</span>", "text/html"); }
        }

        [HttpGet]
        public ActionResult ChangePassword()
        {
            int userid;
            if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) return PartialView("/Account/SignIn", new SignInModel());
            return PartialView(new ChangePasswordModel());
        }

        [HttpPost]
        public ContentResult ChangePassword(ChangePasswordModel model)
        {
            int userid;
            if (Session["userid"] == null || !int.TryParse(Session["userid"].ToString(), out userid)) return Content("<script>window.location.href='/Account/SignIn'</script>", "text/javascript");
            if (!ModelState.IsValid) return Content("<span style='color: red'>Các trường không được để trống</span", "text/html");
            using (var db = new DBContext())
            {
                var account = (from a in db.Accounts
                               where a.Id == userid
                               select a).FirstOrDefault();
                if (account == null) return Content("<span style='color: red'>Không tìm thấy tài khoản</span>", "text/html");
                if (account.Password != model.OldPassword.ToMD5()) return Content("<span style='color: red'>Mật khẩu cũ không đúng</span>", "text/html");
                account.Password = model.NewPassword.ToMD5();
                db.SaveChanges();
            }
            return Content("Đổi mật khẩu thành công", "text/html");
        }
    }
}

EasyAccomod/Views/EditInfo/ChangePassword.cshtml
@model EasyAccomod.Models.ChangePasswordModel

<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<!--Đổi mật khẩu-->
@using (Ajax.BeginForm("ChangePassword", "EditInfo", new AjaxOptions { UpdateTargetId = "change-password-result"}))
{
    <div class="row mt-4">
        @Html.LabelFor(x => x.OldPassword, new { @class = "col-4" })
        @Html.PasswordFor(x => x.OldPassword, new { @class = "col-7 col-sm-6" })
        @Html.ValidationMessageFor(x => x.OldPassword, null, new { @class = "err-msg" })
    </div>
    <div class="row mt-4">
        @Html.LabelFor(x => x.NewPassword, new { @class = "col-4" })
        @Html.PasswordFor(x => x.NewPassword, new { @class = "col-7 col-sm-6" })
        @Html.ValidationMessageFor(x => x.NewPassword, null, new { @class = "err-msg" })
    </div>
    <div class="row mt-4">
        @Html.LabelFor(x => x.RetypeNewPassword, new { @class = "col-4" })
        @Html.PasswordFor(x => x.RetypeNewPassword, new { @class = "col-7 col-sm-6" })
        @Html.ValidationMessageFor(x => x.RetypeNewPassword, null, new { @class = "err-msg" })
    </div>
    <div class="row">
        <div class="col-12">
            <input type="checkbox" id="show-password">
            <label for="show-password">Hiện mật khẩu</label>
        </div>
    </div>
    <div class="row mt-5 justify-content-center">

        <button class="btn btn-primary">Đổi mật khẩu</button>
        <span id="change-password-result" class="col-12 text-center text-success mt-3">
            <!-- Kết quả-->
        </span>


    </div>
    <div class="row justify-content-center">

    </div>
}

<!--Đổi mật khẩu-->

EasyAccomod/Views/EditInfo/Index.cshtml
@{
    ViewBag.Title = "Chỉnh sửa thông tin";
}

@model EasyAccomod.Models.AccountModel
<link href="~/Content/UserInfo.css" rel="stylesheet" />

<div class="container mt-5 rounded" id="edit-info-container" style="margin-top: 50px; margin-bottom: 50px;">
    <div class="row h-100 justify-content-between">
        <div class="col-4 h-100 shadow bg-white rounded" style="padding:0">
            <div class="w-100 row" style="height: 100px; min-height: 100px; margin: 0;flex-wrap: nowrap;">
                <div class="col-3 h-100 align-items-center row justify-content-center" style="margin: 0;">
                    <i class="fas fa-user-circle"></i>
                </div>
                <div id="user-display-name-wrapper" class="col-9 h-100 align-items-center row" style="margin: 0;">
                    <span id="user-display-name">@Model.FullName</span>
                </div>
            </div>
            <div class="w-100 row" style="margin: 0; height: 200px; user-select:none">
                <nav id="info-sidebar">

                    <ul class="list-unstyled components">

                        <li id="user-information" class="nav-item py-2 px-1 px-lg-5 active">
                            Thông tin cá nhân

                        </li>
                        <li id="change-password" class="nav-item py-2 px-1 px-lg-5">
                            Đổi mật khẩu

                        </li>

                    </ul>
                </nav>
            </div>
        </div>
        <div class="col-8 col-sm-7 h-100 bg-white shadow rounded px-0 px-sm-2 pt-5">
            <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
            <script src="~/Scripts/jquery.validate.js"></script>
            <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
            <div id="form-edit-info" class="mt-5 px-0 px-sm-2">
            </div>
        </div>
    </div>

    </div>
    <script>
        // <h3>Model.FullName</h3>
        // Html.Partial("UserInformation", Model)

        $("#info-sidebar ul li").click(function () {
            $(this).addClass("active");
            $(this).siblings().removeClass("active");
        });
        $("#show-password").change(function () {
            if (this.checked) {
                $("#NewPassword").attr("type", "text");
                $("#RetypeNewPassword").attr("type", "text");
            }
            else {
                $("#NewPassword").attr("type", "password");
                $("#RetypeNewPassword").attr("type", "password");
            }
        });
        $("#form-edit-info").load("/EditInfo/UserInformation");

        $("#user-information").click(function () {
            $("#form-edit-info").load("/EditInfo/UserInformation");
        });
        $("#change-password").click(function () {
            $("#form-edit-info").load("/EditInfo/ChangePassword");
        });
    </script>

EasyAccomod/Views/EditInfo/UserInformation.cshtml
@model EasyAccomod.Models.UserInformationModel
<script src="~/Scripts/address.control.js"></script>

@using (Ajax.BeginForm("UserInformation", "EditInfo", new AjaxOptions { UpdateTargetId = "user-information-edit-err-msg" }))
{
    <!--Thoong tin cá nhân-->

    <div class="row mt-4">
        <label for="full-name" class="col-4">Họ và tên</label>
        @if (Model.EditRole)
        {
            <input type="text" id="full-name" name="Fullname" class="col-6" value="@Model.Fullname">
        }
        else
        {
            <input type="text" id="full-name" name="Fullname" class="col-6" value="@Model.Fullname" disabled />
        }
        @Html.ValidationMessageFor(m => m.Fullname, null, new { @class = "err-msg" })
    </div>
    <span class="msg text-danger">
        <!----họ tên sai-->
    </span>
    <div class="row mt-4">
        <label for="phone-number" class="col-4">Số điện thoại</label>
        @if (Model.EditRole)
        {
            <input type="text" id="phone-number" name="Phone" class="col-6" value="@Model.Phone">
        }
        else
        {
            <input type="text" id="phone-number" name="Phone" class="col-6" value="@Model.Phone" disabled>
        }
        @Html.ValidationMessageFor(m => m.Phone, null, new { @class = "err-msg" })
    </div>
    <span class="msg text-danger">
        <!---sdt ko hợp lệ-->
    </span>
    <div class="row mt-4">
        <label for="email" class="col-4">Email</label>
        @if (Model.EditRole)
        {
            <input type="text" id="email" name="Email" class="col-6" value="@Model.Email">
        }
        else
        {
            <input type="text" id="email" name="Email" class="col-6" value="@Model.Email" disabled>
        }
        @Html.ValidationMessageFor(m => m.Email, null, new { @class = "err-msg" })
    </div>
    <div class="row mt-4">
        <label class="col-4">Số CMT</label>
        @if (Model.EditRole)
        {
            <input type="text" class="col-6" name="IdCard" value="@Model.IdCard" />
        }
        else
        {
            <input type="text" class="col-6" name="IdCard" value="@Model.IdCard" disabled />
        }
        @Html.ValidationMessageFor(m => m.IdCard, null, new { @class = "err-msg" })
    </div>
    <div class="row mt-4">
        <label class="col-4">Tỉnh/Thành phố</label>
        <select class="col-6 city-filter" name="CityId">
            <option value="0">Chọn Tình/Thành Phố</option>
        </select>
        @Html.ValidationMessageFor(m => m.CityId, null, new { @class = "err-msg" })
    </div>
    <div class="row mt-4">
        <label class="col-4">Quận/Huyện</label>
        <select class="col-6 district-filter" name="DistrictId">
            <option value="0">Chọn Quận/Huyện</option>
        </select>
        @Html.ValidationMessageFor(m => m.DistrictId, null, new { @class = "err-msg" })
    </div>
    <div class="row mt-4">
        <label class="col-4">Xã Phường</label>
        <select class="col-6 ward-filter" name="WardId">
            <option value="0">Chọn Xã/Phường</option>
        </select>
        @Html.ValidationMessageFor(m => m.WardId, null, new { @class = "err-msg" })
    </div>
    <div class="row mt-4">
        <label class="col-4">Địa chỉ</label>
        @if (Model.EditRole)
        {
            <input type="text" class="col-6" name="Address" value="@Model.Address" />
        }
        else
        {
            <input type="text" class="col-6" name="Address" value="@Model.Address" disabled />
        }
        @Html.ValidationMessageFor(m => m.Address, null, new { @class = "err-msg" })
    </div>
    <span class="msg text-danger">
        <!--email sai-->
    </span>
    <div class="row mt-5 justify-content-center">
        @if (Model.EditRole)
        {
            <button class="btn btn-primary">Cập nhật</button>
        }
        else
        {
            <span>Bạn không được cấp quyền để chỉnh sửa thông tin cá nhân</span> <br />
            <span>Liên hệ admin để được cấp quyền chỉnh sửa thông tin cá nhân</span>
        }
        <span id="user-information-edit-err-msg" class="col-12 text-center text-success mt-3">
        </span>
    </div>
}

@if (!Model.EditRole)
{
    <script>
        loadCity().then(function () { return selectCity(@Model.CityId); })
            .then(function () { return selectDistrict(@Model.DistrictId); })
            .then(function () { return selectWard(@Model.WardId) })
            .then(function () {
                $(".city-filter").prop("disabled", true);
                $(".district-filter").prop("disabled", true);
                $(".ward-filter").prop("disabled", true);
            });
    </script>
}
<script>
    $(document).ready(function () {
        loadCity().then(function () { return selectCity(@Model.CityId); })
            .then(function () { return selectDistrict(@Model.DistrictId); })
            .then(function () { return selectWard(@Model.WardId) });
    });
</script>

<!--Thoong tin cá nhân-->